
import { Database } from "@/integrations/supabase/types";

type TransactionRow = Database['public']['Tables']['transactions']['Row'];

export interface Transaction {
  id: string;
  date: string;
  accountType: string;
  description: string | null;
  value: number;
  type: "credit" | "debit";
  created_at: string;
  updated_at: string;
}

export const accountTypes = [
  "Ajuste de Saldo Crédito",
  "Ajuste de Saldo Débito",
  "Chamada de Capital",
  "Cheque Compensado",
  "Cobrança de Energia",
  "Cobrança de Internet",
  "Cobrança Segurança Condomínio",
  "Cobrança Vaga de Garagem",
  "Consertos Gerais",
  "Consumo de Água",
  "Consumo de Energia",
  "Consumo de Gás",
  "Desconto Concedido",
  "Desconto Recebido",
  "Despesas Bancárias",
  "Estorno de Cheque Compensado",
  "Estorno de Pagamento",
  "Estorno de Recebimento",
  "Fundo de Reserva",
  "Jardinagem",
  "Chaveiro",
  "Outras Conservação e Limpeza",
  "Outras Despesas Fixas",
  "Outras Despesas Manutenção",
  "Outros Encargos Sociais",
  "Pagamento Água",
  "Pagamento Limpeza Fossa",
  "Pagamento Consertos Gerais",
  "Pagamento Contribuição Confederativa",
  "Pagamento Contribuição Sindical",
  "Pagamento DARF",
  "Pagamento de Água",
  "Pagamento de Internet",
  "Pagamento de Multa/Juro",
  "Pagamento Encanador",
  "Pagamento Esc. Contabilidade",
  "Pagamento FGTS",
  "Pagamento Gás",
  "Pagamento INSS",
  "Pagamento Jardineiro",
  "Pagamento Remuneração Síndico",
  "Pagamento Seguro Condomínio",
  "Pagamento Sistema de Gestão",
  "Pagamento Telefonia",
  "Pagamento Título Antecipado",
  "Pagamento Título Pago em Atraso",
  "Pagamento Vigilância",
  "Provisão Férias e 13 Salário",
  "Rateio Ajuste de Saldo Débito",
  "Rateio Cheque Compensado",
  "Rateio Cobrança de Internet",
  "Rateio Cobrança Segurança Condomínio",
  "Rateio Consertos Gerais",
  "Rateio Desconto Concedido",
  "Rateio Despesas Bancárias",
  "Rateio Estorno de Recebimento",
  "Rateio Jardinagem",
  "Rateio Chaveiro",
  "Rateio Outras Conservação e Limpeza",
  "Rateio Outras Despesas Fixas",
  "Rateio Outras Despesas Manutenção",
  "Rateio Outros Encargos Sociais",
  "Rateio Pagamento Água",
  "Rateio Pagamento Auto Fossa",
  "Rateio Pagamento Consertos Gerais",
  "Rateio Pagamento Contribuição Confederativa",
  "Rateio Pagamento Contribuição Sindical",
  "Rateio Pagamento DARF",
  "Rateio Pagamento de Água",
  "Rateio Pagamento de Internet",
  "Rateio Pagamento de Multa/Juro",
  "Rateio Pagamento Encanador",
  "Rateio Pagamento Energia",
  "Rateio Pagamento Esc. Contabilidade",
  "Rateio Pagamento FGTS",
  "Rateio Pagamento Gás",
  "Rateio Pagamento INSS",
  "Rateio Pagamento Jardineiro",
  "Rateio Pagamento Remuneração Síndico",
  "Rateio Pagamento Seguro Condomínio",
  "Rateio Pagamento Sistema de Gestão",
  "Rateio Pagamento Telefonia",
  "Rateio Pagamento Vigilância",
  "Rateio Provisão Férias e 13 Salário",
  "Rateio Saldo Inicial Débito",
  "Rateio Segurança Condomínio",
  "Rateio Tarifa Bancária",
  "Recebimento de Boleto",
  "Recebimento de Boleto em Atraso",
  "Recebimento de Boleto Pago Antecipado",
  "Recebimento de Fatura de Cartão",
  "Recebimento de Multa/Juro",
  "Recebimento Índice",
  "Saldo Inicial Crédito",
  "Saldo Inicial Débito",
  "Segurança Condomínio",
  "Tarifa Bancária",
  "Taxa de Acordo",
  "Taxa de Mudança",
  "Taxa de Uso de Área Comum",
  "Taxa extra",
  "Taxa Quadra de Tênis",
  "Taxa Salão de Festas",
  "Taxa Segunda Via Boleto",
  "Transferência entre contas - entrada",
  "Transferência entre contas - saida",
  "Valor do Condominio"
] as const;
