// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqobeqwijwmkjabmilby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxb2JlcXdpandta2phYm1pbGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzQwMTYsImV4cCI6MjA1NTcxMDAxNn0.jMY1Jj8VpPMo7ZoSfMmuON4L1kBmXfuzdGtY57wvA8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);